/* AUTO-GENERATED by flowers/build_flowers.py — do not edit by hand. */
window.HANA = window.HANA || {};
HANA.flowersBuilt = ["bluebell", "calendula", "chamomile", "dandelion", "echinacea", "elderflower", "forget-me-not", "gardenia", "hibiscus", "honeysuckle", "iris", "jasmine", "lavender", "lily", "lotus", "magnolia", "marigold", "orange-blossom", "passionflower", "peony", "poppy", "rose", "snowdrop", "violet", "wildflower-blend", "yarrow"];
